In [19]:
dados = """ID;Duration;Date;Pulse;Maxpulse;Calories
0;60;'2020/12/01';110;130;4091
1;60;'2020/12/02';117;145;4790
2;60;'2020/12/03';103;135;3400
3;45;'2020/12/04';109;175;2824
4;45;'2020/12/05';117;148;4060
5;60;'2020/12/06';102;127;3000
6;60;'2020/12/07';110;136;3740
7;450;'2020/12/08';104;134;2533
8;30;'2020/12/09';109;133;1951
9;60;'2020/12/10';98;124;2690
10;60;'2020/12/11';103;147;3293
11;60;'2020/12/12';100;120;2507
12;60;'2020/12/12';100;120;2507
13;60;'2020/12/13';106;128;3453
14;60;'2020/12/14';104;132;3793
15;60;'2020/12/15';98;123;2750
16;60;'2020/12/16';98;120;2152
17;60;'2020/12/17';100;120;3000
18;45;'2020/12/18';90;112;NaN
19;60;'2020/12/19';103;123;3230
20;45;'2020/12/20';97;125;2430 2
21;60;'2020/12/21';108;131;3642
22;45;NaN;100;119;2820
23;60;'2020/12/23';130;101;3000
24;45;'2020/12/24';105;132;2460
25;60;'2020/12/25';102;126;3345
26;60;20201226;100;120;2500
27;60;'2020/12/27';92;118;2410
28;60;'2020/12/28';103;132;NaN
29;60;'2020/12/29';100;132;2800
30;60;'2020/12/30';102;129;3803
31;60;'2020/12/31';92;115;2430
"""

with open("dados.csv", "w") as f:
    f.write(dados)

print("Arquivo CSV criado com sucesso!")

Arquivo CSV criado com sucesso!

In [20]:
import pandas as pd

df = pd.read_csv(
    "dados.csv",
    sep=';',
    engine='python',
    encoding='utf-8'
)

In [21]:
df.info()
df.head()
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        32 non-null     int64
 1   Duration  32 non-null     int64
 2   Date      31 non-null     object
 3   Pulse     32 non-null     int64
 4   Maxpulse  32 non-null     int64
 5   Calories  30 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.6+ KB

    ID  Duration          Date  Pulse  Maxpulse Calories
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132      NaN
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

In [24]:
df_clean = df.copy()

In [25]:
df_clean['Calories'] = df_clean['Calories'].fillna(0)
df_clean

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112        0
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21  21        60  '2020/12/21'    108       131     3642
22  22        45           NaN    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132        0
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

In [26]:
df_clean['Date'] = df_clean['Date'].fillna('1900/01/01')
df_clean

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112        0
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21  21        60  '2020/12/21'    108       131     3642
22  22        45    1900/01/01    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132        0
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

In [27]:
df_clean['Date'] = pd.to_datetime(df_clean['Date'])

ValueError: time data "1900/01/01" doesn't match format "'%Y/%m/%d'", at position 22. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [28]:
df_clean['Date'] = df_clean['Date'].replace('1900/01/01', pd.NaT)

In [29]:
df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%Y/%m/%d', errors='coerce')
df_clean

    ID  Duration Date  Pulse  Maxpulse Calories
0    0        60  NaT    110       130     4091
1    1        60  NaT    117       145     4790
2    2        60  NaT    103       135     3400
3    3        45  NaT    109       175     2824
4    4        45  NaT    117       148     4060
5    5        60  NaT    102       127     3000
6    6        60  NaT    110       136     3740
7    7       450  NaT    104       134     2533
8    8        30  NaT    109       133     1951
9    9        60  NaT     98       124     2690
10  10        60  NaT    103       147     3293
11  11        60  NaT    100       120     2507
12  12        60  NaT    100       120     2507
13  13        60  NaT    106       128     3453
14  14        60  NaT    104       132     3793
15  15        60  NaT     98       123     2750
16  16        60  NaT     98       120     2152
17  17        60  NaT    100       120     3000
18  18        45  NaT     90       112        0
19  19        60  NaT    103       123     3230
20  20        45  NaT     97       125   2430 2
21  21        60  NaT    108       131     3642
22  22        45  NaT    100       119     2820
23  23        60  NaT    130       101     3000
24  24        45  NaT    105       132     2460
25  25        60  NaT    102       126     3345
26  26        60  NaT    100       120     2500
27  27        60  NaT     92       118     2410
28  28        60  NaT    103       132        0
29  29        60  NaT    100       132     2800
30  30        60  NaT    102       129     3803
31  31        60  NaT     92       115     2430

In [30]:
df_clean['Date'] = df_clean['Date'].replace('20201226', '2020/12/26')
df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%Y/%m/%d', errors='coerce')

In [31]:
df_clean = df_clean.dropna(subset=['Date'])
df_clean

Empty DataFrame
Columns: [ID, Duration, Date, Pulse, Maxpulse, Calories]
Index: []